export const LOGIN_USER = "LOGIN_USER";
export const DELETE_USER = "DELETE _USER";
export const DELETE_ROLE = "DELETE _ROLE";
export const SET_ROLE_TO_USER = "SET_ROLE_TO_USER"
export const SET_PERMISSION_TO_ROLE = "SET_PERMISSION_TO_ROLE"
export const ADD_NEW_PERMISSION = "ADD_NEW_PERMISSION"
export const DELETE_PERMISSION = "DELETE_PERMISSION"