export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER_EMAIL = "GET_USER_EMAIL";
export const FETCH_NAVIGATION_ADMIN = "FETCH_NAVIGATION_ADMIN";
export const FETCH_NAVIGATION_EMPLOYEE = "FETCH_NAVIGATION_EMPLOYEE";
export const CATCH_ERROR = "CATCH_ERROR";
export const SET_ADMIN_USER = "SET_ADMIN_USER";
export const SET_ADMIN_LIST = "SET_ADMIN_LIST";
export const LOADING_STATE = "LOADING_STATE";
export const SET_MESSAGE = "SET_MESSAGE";
// Doctor

export const SET_FORGOT_USER = "SET_FORGOT_USER";

export const SET_FORGOT_USERS = "SET_FORGOT_USERS";

export const SET_TAG_OPTIONS = "SET_TAG_OPTIONS";
export const GET_TAG_OPTIONS = "GET_TAG_OPTIONS";
export const ADD_TAG = "ADD_TAG";
export const SEARCH_TAG = "SEARCH_TAG";
export const REMOVE_TAG = "REMOVE_TAG";

export const GET_FEELING_OPTIONS = "GET_FEELING_OPTIONS";
export const SET_FEELING_OPTIONS = "SET_FEELING_OPTIONS";
export const ADD_FEELINNG = "ADD_FEELINNG";
export const SEARCH_FEELING = "SEARCH_FEELING"

